### ISSUE TITLE
Plugin Error is causing JellyFin to Crash

### ISSUE THREAD

**Issue by feerlessleadr** [jellyfin/jellyfin-plugin-tmdbboxsets#16]
Hi - new to JF and testing it out. I installed the box set plugin, and it seems that every time it tries to create a box set for Bill & Ted, it causes JF to crash. Here is the relevant bit from the JF log:

```
[2020-05-14 02:01:13.022 -04:00] [INF] [19] App: Box Set for "Bill &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Ted's Most Excellent Collection" ("91746") does not exist. Creating it now!
[2020-05-14 02:01:13.028 -04:00] [FTL] [19] Main: Unhandled Exception
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\ProgramData\Jellyfin\Server\data\collections\Bill &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Ted's Most Excellent Collection [boxset]'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Emby.Server.Implementations.Collections.CollectionManager.CreateCollection(CollectionCreationOptions options)
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.AddMoviesToCollection(IReadOnlyCollection`1 movies, String tmdbCollectionId, BoxSet boxSet)
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

Thanks

**Comment by danimart1991** [comment]
I think [Release 8](https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets/releases/tag/v8) fix this problem. Could you test it?
