### ISSUE TITLE
plugin doesnt work in the currently nightly

### ISSUE THREAD

**Issue by ikomhoog** [jellyfin/jellyfin-plugin-tmdbboxsets#20]
To clarify, on the current release it works, but on the nightly build it doesnt.
i dont know if this is a nightly issue, or if its a change in the upcoming jellyfin version.

on nightly i get an error and in the logs it shows this:
```
[2020-06-05 12:41:47.853 +02:00] [ERR] [17] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.mydomain.com/TMDbBoxSets/Refresh"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.TMDbBoxSets.Api.TMDbCollectionsService'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstance(Type type)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.CreateInstance(Type type)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by crobibero** [comment]
Plugins don’t normally work for nightly, we will have to do a pass-over and update them all to fix the breaking changes

**Comment by ikomhoog** [comment]
ohh i didnt know, thanks for the info.
