### ISSUE TITLE
Not compatible with Jellyfin 10.5.0

### ISSUE THREAD

**Issue by Bond-009** [jellyfin/jellyfin-plugin-tmdbboxsets#7]
Crashes on startup:
```
Unhandled Exception
System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Entities.InternalItemsQuery.set_OrderBy(System.ValueTuple`2<System.String,MediaBrowser.Model.Entities.SortOrder>[])'.
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.GetMoviesFromLibrary()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.OnTimerElapsed()
   at Jellyfin.Plugin.TMDbBoxSets.TMDbBoxSetManager.<.ctor>b__5_0(Object _)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

**Comment by Bond-009** [comment]
And it's a duplicate of #6
